### ISSUE TITLE
add a github work flow that npm publishes when merge to main

### ISSUE THREAD

**Issue by jtushman** [jtushman/babar#4]

**Comment by ChristopherAlphonse** [comment]
Can you create an NPM token and provide me the secret name so I can create the ci file

**Comment by jtushman** [comment]
created...
called it NPM_TOKEN

can be reference like the following

```
name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```
